update ports script

diff --git a/ports b/ports
--- a/ports
+++ b/ports
@@ -1,29 +1,30 @@
 #!/bin/bash
 
 get_portpath() {
-	local r
+	local port=$1
 	
-	if [ -z "$portname" ]; then
+	if [ -z "$port" ]; then
 		echo "Please define port name."
 		exit 2
 	fi
 	
 	for r in ${PORTREPO[@]}; do
-		if [ -f $r/$portname/spkgbuild ]; then
-			portpath=$r/$portname
+		if [ -f $r/$port/spkgbuild ]; then
+			portpath=$r/$port
 			break
 		fi
 	done
 	
 	if [ -z "$portpath" ]; then
-		echo "Port '$portname' not exist."
+		echo "Port '$port' not exist."
 		exit 1
 	fi
 }
 
-reset_changes() {
+revert_changes() {
 	echo -n "Error occurs. Do you want to revert changes? Y/n "
 	read -n1 input
+	echo
 	
 	case $input in
 		N|n) echo "Changes is kept.";;
@@ -51,10 +52,13 @@ get_depends() {
 	| sed 's/,//'
 }
 
-update_port() {
-	get_portpath
+port_update() {
+	local port=$1
+	local vers=$2
 	
-	if [ -z "$upversion" ]; then
+	get_portpath $port
+	
+	if [ -z "$vers" ]; then
 		echo "Please define version to update."
 		exit 2
 	fi
@@ -102,30 +106,91 @@ update_port() {
 		done
 	done			
 	
-	fakeroot pkgbuild -o || reset_changes
-	fakeroot pkgbuild -g || reset_changes
-	fakeroot pkgbuild    || reset_changes
-	fakeroot pkgbuild -p || reset_changes
+	fakeroot pkgbuild -o || revert_changes
+	fakeroot pkgbuild -g || revert_changes
+	fakeroot pkgbuild    || revert_changes
+	fakeroot pkgbuild -p || revert_changes
 	sudo pkgbuild -uv
 	
 	popd >/dev/null
 }
 
-commit_port() {
-	if [ -z "$portname" ]; then
-		for port in $(git diff --name-only ${PORTREPO[@]} | awk -F / '{print $2}' | uniq); do
-			portname=$port
-			commit_port2
+port_build() {
+	local port=$1; shift
+	opt=$(extract_opt $@)
+	
+	for i in $opt; do
+		if [[ $i =~ -(i|u|r) ]]; then
+			continue # filter out install/upgrade/reinstall
+		else
+			opts+=" $i"
+		fi
+	done
+	
+	get_portpath $port
+	
+	deps=$(get_depends)
+	for d in $deps; do
+		found=0
+		if ! isinstalled $d; then
+			echo "Dependency not installed: $d"
+			for r in ${PORTREPO[@]}; do
+				if [ -f "$r/$d/spkgbuild" ]; then
+					found=1
+					break
+				fi
+			done
+			if [ "$found" != 1 ]; then
+				echo "Missing dependency port: $d"
+			fi
+			exit 1
+		fi
+	done
+	
+	pushd $portpath >/dev/null
+	
+	while true; do
+	cat spkgbuild | more
+	echo
+	
+		while true; do
+			echo -n "[E]dit [A]bort [C]ontinue ? "
+			read -n1 input
+			echo
+			case $input in
+				E|e) vim spkgbuild
+				     break 1;;
+				A|a) exit 1;;
+				*)   break 2;;
+			esac
 		done
+	done			
+	
+	fakeroot pkgbuild $opts || return $?
+	
+	popd >/dev/null
+}
+
+port_commit() {
+	local port=$1; shift
+	cmsg=$@
+	
+	if [ -z "$port" ]; then
+		for p in $(git diff --name-only ${PORTREPO[@]} | awk -F / '{print $2}' | uniq); do
+			commit_port $p
+		done
+	elif ! git diff --name-only ${PORTREPO[@]} | awk -F / '{print $2}' | grep -qx $port; then
+		echo "Nothing to commit about '$port'"
+		exit 4
 	else
-		commit_port2
+		commit_port $port
 	fi	
 }
 
-commit_port2() {
-	get_portpath
+commit_port() {
+	local port=$1; shift
 	
-	pushd $portpath >/dev/null
+	get_portpath $port
 	
 	deps=$(get_depends)
 	for d in $deps; do
@@ -144,21 +209,27 @@ commit_port2() {
 	
 	[ "$missing" = 1 ] && exit 1
 	
-	. spkgbuild
-	commitmsg="$name: updated to $version"
+	pushd $portpath >/dev/null
 	
-	echo "Generate .checksums for $name..."
+	if [ -z "$cmsg" ]; then
+		. spkgbuild
+		cmsg="updated to $version"
+	fi
+	
+	echo "Generate .checksums for $port..."
 	fakeroot pkgbuild -g
-	echo "Generate .pkgfiles for $name..."
+	echo "Generate .pkgfiles for $port..."
 	fakeroot pkgbuild -p
 	
 	git add .
-	git commit -m "$commitmsg"
+	git commit -m "$port: $cmsg"
+	
+	unset cmsg
 	
 	popd >/dev/null
 }
 
-repgen_repo() {
+port_repgen() {
 	if [ ! $(type -pa httpup-repgen) ]; then
 		echo "httpup not installed, aborting"
 		exit 1
@@ -169,7 +240,7 @@ repgen_repo() {
 	done
 }
 
-push_repo() {
+port_push() {
 	#if git status | grep "Your branch is up to date"; then
 	#	return 0
 	#fi
@@ -180,7 +251,7 @@ push_repo() {
 		return 2
 	fi
 	
-	repgen_repo
+	port_repgen
 	
 	for r in ${PORTREPO[@]}; do
 		git add $r
@@ -190,8 +261,10 @@ push_repo() {
 	git push
 }
 
-diff_repo() {
-	get_portpath
+port_diff() {
+	local port=$1
+	
+	get_portpath $port
 	
 	pushd $portpath >/dev/null
 
@@ -200,88 +273,50 @@ diff_repo() {
 	popd >/dev/null
 }
 
-show_status() {
+port_status() {
 	git status | grep "Your branch is ahead of" && echo
 	git status | grep -v REPO | grep modified | sed 's/.*modified:/modified:/g'
 }
 
-showhelp() {
+extract_opt() {
+	for opt in $@; do
+		case $opt in
+			  --*) BOPTS+=($opt) ;;
+			   -*) for (( i=1; i<${#opt}; i++ )); do BOPTS+=(-${opt:$i:1}); done ;;
+			    *) BOPTS+=($opt) ;;
+		esac
+	done
+	echo ${BOPTS[@]}
+}
+
+port_help() {
 	cat << EOF
 Usage:
   $(basename $0) <options> [ arg ]
   
 Options:
-  -u <portname> <newversion>   update ports to <newversion>
-  -c <portname>                commit port's update changes
-  -d <portname>                show diff of ports
-  -r                           update REPO file
-  -p                           push all updates
-  -s                           show current status
-  -h                           show this help message
+  update <portname> <newversion>   update ports to <newversion>
+  commit <portname> <commit msg>   commit port's update changes
+  diff   <portname>                show diff of ports
+  repgen                           update REPO file
+  push                             push all updates
+  status                           show current status
+  help                             show this help message
       
 EOF
-}
-
-parseopt() {
-	while [ "$1" ]; do
-		case $1 in
-			-u) updateport=1
-			    portname=$2
-			    upversion=$3
-			    shift 2;;
-			-c) commitchanges=1
-			    portname=$2
-			    shift ;;
-			-r) repgenrepo=1;;
-			-p) pushrepo=1;;
-			-d) diffrepo=1
-			    portname=$2
-			    shift;;
-			-s) showstatus=1;;
-			-h) showhelp;;
-			*)  echo "Run '$(basename $0) -h' to see available options."; exit 1;;
-		esac
-		shift
-	done
-}
-
-main() {
-	parseopt $@
-	
-	if [ "$updateport" ]; then
-		update_port
-		return 0
-	fi
-	
-	if [ "$commitchanges" ]; then
-		commit_port
-		return 0
-	fi
-	
-	if [ "$repgenrepo" ]; then
-		repgen_repo
-		return 0
-	fi
-	
-	if [ "$diffrepo" ]; then
-		diff_repo
-		return 0
-	fi
-	
-	if [ "$pushrepo" ]; then
-		push_repo
-		return 0
-	fi
-	
-	if [ "$showstatus" ]; then
-		show_status
-		return 0
-	fi
 }
 
 PORTREPO=(core extra multilib xorg community)
 INDEX_DIR="/var/lib/scratchpkg/index"
 
-main $@
+OP=$1
+shift
+
+if [ $(type -t port_$OP) ]; then
+	port_$OP $@
+else
+	port_help
+	exit 1
+fi
 
 exit $?
